# Copyright (c) 2025-2026, The Isaac Lab Arena Project Developers (https://github.com/isaac-sim/IsaacLab-Arena/blob/main/CONTRIBUTORS.md).
# All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

# This file shows how to configure the Gr00tClosedloopPolicy class for GR1 tabletop manipulation task
# NOTE(alexmillane, 2025-10-31): The model path here aligns with the model used in the static manipulation tutorial.
model_path: /models/isaaclab_arena/sequential_static_manipulation_tutorial/ranch_bottle_into_fridge/
language_instruction: "Place the sauce bottle on the top shelf of the fridge, and close the fridge door."
# Action horizon is the number of actions predicted by the policy per inference rollout, defined in the GN1.6 policy data_config 'fourier_gr1_arms_only'.
action_horizon: 16
embodiment_tag: GR1
video_backend: decord
modality_config_path: isaaclab_arena_gr00t/embodiments/gr1/gr1_arms_only_data_config.py

policy_joints_config_path: isaaclab_arena_gr00t/embodiments/gr1/gr00t_26dof_joint_space.yaml
action_joints_config_path: isaaclab_arena_gr00t/embodiments/gr1/36dof_joint_space.yaml
state_joints_config_path: isaaclab_arena_gr00t/embodiments/gr1/54dof_joint_space.yaml

# Action chunk length is the number of actions executed per inference rollout, could be less than action_horizon.
action_chunk_length: 16
task_mode_name: gr1_tabletop_manipulation

pov_cam_name_sim: "robot_pov_cam_rgb"

original_image_size: [512, 512, 3]
target_image_size: [512, 512, 3]
